FROM node:20.9
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --production --omit=dev
RUN npm i -g serve
RUN chown -R node /app
EXPOSE 3006
USER node
CMD ["serve", "-s", "build", "-l", "3006"]